name: first
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.1

  # Android Usage Stats
  app_usage: ^3.0.1

  # Device Apps (for app names and icons)
  device_apps: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Regular.ttf
        - asset: fonts/Jost-Bold.ttf
          weight: 700